### ISSUE TITLE
Local flag broken

### ISSUE THREAD

**Issue by ghost** [dbbs-lab/astrocyte#13]
```
(thesis) lorenzo@DESKTOP-KPG0D2J:~/thesis/nav18mut$ astro add mod nav18cw.mod --name Nav1_8 --variant=cw --local
Traceback (most recent call last):
  File "/home/lorenzo/.pyenv/versions/thesis/bin/astro", line 8, in <module>
    sys.exit(astrocyte_cli())
  File "/home/lorenzo/.pyenv/versions/3.9.10/envs/thesis/lib/python3.9/site-packages/astrocyte/cli.py", line 188, in astrocyte_cli
    cl_args.func(cl_args)
  File "/home/lorenzo/.pyenv/versions/3.9.10/envs/thesis/lib/python3.9/site-packages/astrocyte/cli.py", line 276, in add_mod_file
    pkg = _get_pkg(args)
  File "/home/lorenzo/.pyenv/versions/3.9.10/envs/thesis/lib/python3.9/site-packages/astrocyte/cli.py", line 270, in _get_pkg
    return load_local_pkg()
  File "/home/lorenzo/.pyenv/versions/3.9.10/envs/thesis/lib/python3.9/site-packages/astrocyte/__init__.py", line 591, in load_local_pkg
    local = create_package(
  File "/home/lorenzo/.pyenv/versions/3.9.10/envs/thesis/lib/python3.9/site-packages/astrocyte/cli.py", line 216, in create_package
    os.mkdir(folder)
FileNotFoundError: [Errno 2] No such file or directory: '/home/lorenzo/.local/share/Astrocyte/local'
(thesis) lorenzo@DESKTOP-KPG0D2J:~/thesis/nav18mut$ mkdir -p /home/lorenzo/.local/share/Astrocyte/local
(thesis) lorenzo@DESKTOP-KPG0D2J:~/thesis/nav18mut$ astro add mod nav18cw.mod --name Nav1_8 --variant=cw --local
ERROR This directory is not a glia package.
```

**Comment by Helveg** [comment]
This will be fixed in https://github.com/dbbs-lab/glia/pull/50
